apiVersion: v1
kind: Service
metadata:
  name: balo-cricket-frontend
  namespace: balo-cricket
  labels:
    app: balo-cricket-frontend
spec:
  selector:
    app: balo-cricket-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
