apiVersion: apps/v1
kind: Deployment
metadata:
  name: balo-cricket-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "balo-cricket.api.selectorLabels" . | nindent 4 }}
    {{- include "balo-cricket.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "balo-cricket.api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "balo-cricket.api.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      containers:
        - name: balo-cricket-api
          image: {{ include "balo-cricket.api.image" . }}
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.api.service.targetPort }}
          envFrom:
            - secretRef:
                name: api-secrets
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.api.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.api.service.targetPort }}
            initialDelaySeconds: 20
            periodSeconds: 20
