apiVersion: apps/v1
kind: Deployment
metadata:
  name: balo-cricket-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "balo-cricket.frontend.selectorLabels" . | nindent 4 }}
    {{- include "balo-cricket.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "balo-cricket.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "balo-cricket.frontend.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      containers:
        - name: balo-cricket-frontend
          image: {{ include "balo-cricket.frontend.image" . }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.targetPort }}
          env:
            - name: REACT_APP_API_URL
              value: {{ .Values.frontend.env.REACT_APP_API_URL | quote }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.service.targetPort }}
            initialDelaySeconds: 15
            periodSeconds: 20
