apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "balo-cricket.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.api.secrets.jwtSecret | quote }}
  API_KEY: {{ .Values.api.secrets.apiKey | quote }}
